=== claydiffrient/HelpDoc/helpdoc.dtd
<!ELEMENT helpnavigation (title+)>
<!ELEMENT title (document+)>
<!ELEMENT document (document*)>


<!ATTLIST document ref CDATA #REQUIRED>
<!ATTLIST document title CDATA #REQUIRED>
<!ATTLIST document id CDATA #REQUIRED>
<!ATTLIST title title CDATA #REQUIRED>
<!ATTLIST title id CDATA #REQUIRED>
<!ATTLIST title ref CDATA #IMPLIED>

=== claydiffrient/HelpDoc/helpdoc-old.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE helpnavigation SYSTEM "helpdoc.dtd">
<helpnavigation>
   <title id="0" name="Overview">
	   <document id="0-0" title="Overview" ref="http://byui.brainhoney.com/resource/14853/Web/help/Overview.vhtml" />
	</title>
   <title id="1" name="Student">
	  <document id="1-0" title="Student Dashboard">
         <document id="1-0-0" ref="http://byui.brainhoney.com/resource/14853/Web/help/GradebookActivity.vhtml" title="Gradebook Activity" />
         <document id="1-0-1" ref="http://byui.brainhoney.com/resource/14853/Web/help/CourseListStudent.vhtml" title="Course List" />
         <document id="1-0-2" ref="http://byui.brainhoney.com/resource/14853/Web/help/DueSoon.vhtml" title="Due Soon" />
    	 <document id="1-0-3" ref="http://byui.brainhoney.com/resource/14853/Web/help/Announcements.vhtml" title="Announcements" />
	  </document>
	  <document id="1-1" ref="http://byui.brainhoney.com/resource/14853/Web/help/Transcript.vhtml" title="Transcript" />
   </title>
   <title id="2" name="Teacher">
      <document id="2-0" title="Teacher Dashboard">
	     <document id="2-0-0" ref="http://byui.brainhoney.com/resource/14853/Web/help/AnnouncementsTeacher.vhtml" title="Announcements" />
	     <document id="2-0-1" ref="http://byui.brainhoney.com/resource/14853/Web/help/CourseListTeacher.vhtml" title="Course List" />
	  </document>
	  <document id="2-1" title="Maybe coming...">
         <document id="2-1-1" ref="http://byui.brainhoney.com/resource/14853/Web/help/GradebookQuickview.vhtml" title="Gradebook Quickview" />
      </document>
   </title>
   <title id="3" name="Observer">
   </title>
</helpnavigation>

=== claydiffrient/HelpDoc/helpdoc.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE helpnavigation SYSTEM "helpdoc.dtd">
<helpnavigation>
   <title id="0" name="General I-Learn">
      <document id="0-1" ref="http://byui.brainhoney.com/resource/14853/Web/help/Announcements.vhtml" title="Announcements" />
   </title>
   <title id="1" name="Student Dashboard">
      <document id="1-1" ref="http://byui.brainhoney.com/resource/14853/Web/help/GradebookActivity.vhtml" title="Gradebook Activity" />
      <document id="1-2" ref="http://byui.brainhoney.com/resource/14853/Web/help/CourseListStudent.vhtml" title="Course List" />
      <document id="1-3" ref="http://byui.brainhoney.com/resource/14853/Web/help/DueSoon.vhtml" title="Due Soon" />
      <document id="1-4" ref="http://byui.brainhoney.com/resource/14853/Web/help/Transcript.vhtml" title="Transcript">
         <document id="1-4-1" ref="http://byui.brainhoney.com/resource/14853/Web/help/Default.vhtml" title="Something">
            <document id="1-4-1-1" ref="http://byui.brainhoney.com/resource/14853/web/component/calendar/mastercal.vhtml" title="calendar">
               <document id="1-4-1-1-1" ref="http://byui.brainhoney.com/resource/14853/web/component/eyelearn/eyelearn.vhtml" title="calendar" />
            </document>
         </document>
      </document>
   </title>
   <title id="2" name="Teacher Dashboard">
      <document id="2-1" ref="http://byui.brainhoney.com/resource/14853/Web/help/CourseListTeacher.vhtml" title="Course List" />
      <document id="2-2" ref="http://byui.brainhoney.com/resource/14853/Web/help/GradebookQuickview.vhtml" title="Gradebook Quickview" />
   </title>
</helpnavigation>
